[build]
  command = "cd .. && npm install --prefix web && npm run build --prefix web"
  publish = "web/.next"

[build.environment]
  NEXT_PUBLIC_SUPABASE_URL = "https://flridnddurlnkxmdfhym.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "sb_publishable_akanXSWtwBMbkHlmltAkTg_n88NayFz"

[[plugins]]
  package = "@netlify/plugin-nextjs"
